language: cpp
dist: trusty
compiler:
    - gcc
    - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
	- llvm-toolchain-trusty-4.0
    packages:
    - g++-6
    - clang-4.0

script: 
  - $CXX --version
